from __future__ import annotations

import concurrent.futures
import json
import random
import re
import time
from datetime import datetime
from pathlib import Path
from typing import Any
from uuid import uuid4

from magi.config import Settings
from magi.providers import Provider
from magi.types import LLMResult

from .prompts import AGENT_SYSTEMS, AUDITOR_SYSTEM, JUDGE_SYSTEM, agent_prompt, auditor_prompt, judge_prompt

AGENT_PROVIDER = {"MELCHIOR": "openai", "BALTHASAR": "anthropic", "CASPER": "gemini"}


#       /\_/\
#      ( o.o )  Check twice. Claim once.
#       > ^ <
def _parallel(jobs: dict[str, tuple[Provider, str, str]]) -> dict[str, LLMResult]:
    output: dict[str, LLMResult] = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(jobs)) as executor:
        futures = {executor.submit(p.generate, s, u): name for name, (p, s, u) in jobs.items()}
        for future in concurrent.futures.as_completed(futures):
            name = futures[future]
            try:
                output[name] = future.result()
            except Exception as exc:
                provider = jobs[name][0]
                output[name] = LLMResult(
                    provider=provider.name,
                    model=provider.model,
                    text="",
                    latency_seconds=0.0,
                    error=f"{type(exc).__name__}: {exc}",
                    status="error",
                )
    return output


def _clean_json(text: str) -> str:
    cleaned = text.strip()
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    start, end = cleaned.find("{"), cleaned.rfind("}")
    return cleaned[start : end + 1] if start >= 0 and end > start else cleaned


def parse_report(text: str) -> tuple[dict[str, Any] | None, str | None]:
    try:
        payload = json.loads(_clean_json(text))
        if payload.get("verdict") not in {"PASS", "REVISE", "BLOCK"}:
            raise ValueError("verdict non valido")
        payload["internal_confidence"] = max(0, min(100, int(round(float(payload.get("internal_confidence", 0))))))
        for key in ("critical_issues", "moderate_issues", "strengths", "missing_information", "disagreements_resolved", "next_actions"):
            if not isinstance(payload.get(key), list):
                payload[key] = []
        return payload, None
    except Exception as exc:
        return None, f"{type(exc).__name__}: {exc}"


def report_markdown(report: dict[str, Any], source_name: str, profile: str) -> str:
    lines = [
        "# BioAudit Report",
        "",
        f"**Verdict:** {report['verdict']}",
        f"**Profile:** {profile}",
        f"**Source:** {source_name}",
        f"**Internal confidence:** {report.get('internal_confidence', 0)}%",
        "",
        "## Summary",
        "",
        str(report.get("summary", "")),
    ]

    def issue_section(title: str, items: list[Any]) -> None:
        lines.extend(["", f"## {title}", ""])
        if not items:
            lines.append("None identified from the supplied input.")
            return
        for index, item in enumerate(items, start=1):
            if not isinstance(item, dict):
                lines.append(f"{index}. {item}")
                continue
            lines.extend([
                f"### {index}. {item.get('title', 'Issue')}",
                f"- **Evidence:** {item.get('evidence_from_input', 'Not specified')}",
                f"- **Why it matters:** {item.get('why_it_matters', '')}",
                f"- **Recommended fix:** {item.get('recommended_fix', '')}",
                f"- **Verification:** {item.get('verification', '')}",
                "",
            ])

    issue_section("Critical issues", report.get("critical_issues", []))
    issue_section("Moderate issues", report.get("moderate_issues", []))
    for title, key in (
        ("Strengths", "strengths"),
        ("Missing information", "missing_information"),
        ("Disagreements resolved", "disagreements_resolved"),
        ("Next actions", "next_actions"),
    ):
        lines.extend(["", f"## {title}", ""])
        items = report.get(key, [])
        if items:
            lines.extend(f"{index}. {item}" for index, item in enumerate(items, start=1))
        else:
            lines.append("None.")
    lines.extend(["", "---", "Internal confidence is generated by the judge and is not a validated probability of correctness."])
    return "\n".join(lines) + "\n"


class BioAuditOrchestrator:
    def __init__(self, settings: Settings, providers: dict[str, Provider]) -> None:
        self.settings = settings
        self.providers = providers

    def run(
        self,
        text: str,
        profile: str = "eeg_ml",
        auditor: bool = True,
        blind: bool = True,
        seed: int = 20260806,
        output_root: Path = Path("bioaudit_results"),
        source_name: str = "input",
    ) -> tuple[dict[str, Any], Path]:
        if profile not in {"eeg_ml", "biomedical", "general_ml"}:
            raise ValueError("Profilo non valido")
        text = text.strip()
        if len(text) < 20:
            raise ValueError("L'input è troppo breve per un audit utile.")
        started = time.perf_counter()
        jobs = {
            agent: (self.providers[provider], AGENT_SYSTEMS[agent], agent_prompt(text, profile, agent))
            for agent, provider in AGENT_PROVIDER.items()
        }
        agent_results = _parallel(jobs)
        names = list(agent_results)
        if blind:
            random.Random(seed).shuffle(names)
        labels = [f"CANDIDATE_{chr(65+i)}" for i in range(len(names))]
        candidate_map = dict(zip(labels, names, strict=True))
        candidates = {
            label: agent_results[name].text if not agent_results[name].error else f"ERRORE: {agent_results[name].error}"
            for label, name in candidate_map.items()
        }
        calls = list(agent_results.values())
        audit_result: LLMResult | None = None
        if auditor:
            audit_provider = self.providers[self.settings.auditor_provider]
            audit_result = audit_provider.generate(AUDITOR_SYSTEM, auditor_prompt(text, profile, candidates))
            calls.append(audit_result)
        judge = self.providers[self.settings.judge_provider]
        verdict = judge.generate(
            JUDGE_SYSTEM,
            judge_prompt(text, profile, candidates, audit_result.text if audit_result and not audit_result.error else None),
        )
        calls.append(verdict)
        parsed, parse_error = parse_report(verdict.text)
        if parsed is None:
            parsed = {
                "verdict": "REVISE",
                "summary": "Il report strutturato non è stato interpretato correttamente.",
                "critical_issues": [],
                "moderate_issues": [],
                "strengths": [],
                "missing_information": [parse_error or "Errore di parsing"],
                "disagreements_resolved": [],
                "next_actions": ["Controllare l'output grezzo del giudice."],
                "internal_confidence": 0,
            }
        run_id = datetime.now().strftime("%Y%m%d-%H%M%S") + "-" + uuid4().hex[:8]
        directory = output_root / run_id
        directory.mkdir(parents=True, exist_ok=False)
        metadata = {
            "run_id": run_id,
            "created_at": datetime.now().isoformat(),
            "profile": profile,
            "source_name": source_name,
            "auditor_enabled": auditor,
            "blind_enabled": blind,
            "candidate_map": candidate_map,
            "wall_time_seconds": round(time.perf_counter() - started, 3),
            "parse_error": parse_error,
            "calls": [call.to_dict() for call in calls],
            "agents": {name: result.to_dict() for name, result in agent_results.items()},
            "auditor": audit_result.to_dict() if audit_result else None,
            "judge": verdict.to_dict(),
            "report": parsed,
        }
        (directory / "report.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
        (directory / "report.md").write_text(report_markdown(parsed, source_name, profile), encoding="utf-8")
        (directory / "input.txt").write_text(text, encoding="utf-8")
        return metadata, directory
